services:
    instagram.image.repository:
        class: 'AppBundle\Entity\ImageRepository'
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - 'AppBundle\Entity\Image'
    instagram.configuration.repository:
        class: 'AppBundle\Entity\ConfigurationRepository'
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - 'AppBundle\Entity\Configuration'