services:
    instagram.image.repository:
        class: 'AppBundle\Entity\ImageRepository'
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - 'AppBundle\Entity\Image'

#  instagram.campaign.form_type:
#      class: AppBundle\Form\ReplyFormType
#      arguments: ["@instagram.media.flysystem","%kernel.media_symlink%"]
#      tags:
#        - { name: form.type, alias: instagram_reply }
#  instagram.media.flysystem.adapter:
#      class: League\Flysystem\Adapter\Local
#      arguments: ["%kernel.media_dir%"]
#      public: false
#  instagram.media.flysystem:
#      class: League\Flysystem\Filesystem
#      arguments: ["@instagram.media.flysystem.adapter"]


